#!/usr/bin/env python3
"""EOS SDK project generator and project inspector."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

IDENTIFIER = re.compile(r"^[a-z][a-z0-9]*(?:\.[a-z0-9]+)+$")
ROUTE = re.compile(r"^[a-z][a-z0-9_.-]*$")

ICON = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#314f89"/><circle cx="32" cy="32" r="16" fill="#f6f8ff"/></svg>\n'
SPLASH = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180"><rect width="320" height="180" fill="#101522"/><text x="160" y="96" text-anchor="middle" fill="#f6f8ff" font-size="24">EOS</text></svg>\n'


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def base_manifest(bundle_id: str, author: str, title: str) -> dict:
    return {
        "format": "eapp", "format_version": 3,
        "identity": {"bundle_id": bundle_id, "publisher": "Etternhall Labs", "author": author},
        "name": title, "version": "0.1.0", "api": "elang-0.2", "min_eos": ">=0.1.0",
        "entrypoint": "bin/main.eosbc",
        "ui": {"entry": "ui/home.eosui", "framework": "eos-ui-0.1"},
        "activities": {"main": "app.home", "definitions": [{
            "id": "app.home", "title": title, "ui": "ui/home.eosui", "entry": "on_home_create",
            "exported": True, "orientation": "any", "restore": True
        }]},
        "targets": ["eos-x86_64", "eos-aarch64"],
        "resources": {"icon": "resources/icon.svg", "splash": "resources/splash.svg", "docs": "docs/README.md", "license": "LICENSE"},
        "libraries": {"eos.ui": "0.1", "eos.storage": "0.1", "eos.navigation": "0.1", "eos.lifecycle": "0.1"},
        "policy": {"permissions": "policy/permissions.yml", "triggers": "policy/triggers.yml"},
        "signatures": {"manifest": "signatures/manifest.mf", "payload": "signatures/payload.mf"},
        "license": "UNLICENSED-development", "payload_sha256": None, "created_by": "eos-sdk/0.2"
    }


def create_project(bundle_id: str, root: Path, author: str, title: str) -> None:
    if root.exists() and any(root.iterdir()):
        raise SystemExit(f"eos-sdk error: output directory is not empty: {root}")
    for directory in ("src", "ui", "styles", "animations", "policy", "resources", "docs", "signatures"):
        (root / directory).mkdir(parents=True, exist_ok=True)
    manifest = base_manifest(bundle_id, author, title)
    write(root / "eapp.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    write(root / "src/main.elang", f'''app {bundle_id}
version "0.1.0"
use eos.ui as ui
use eos.navigation as navigation
use eos.lifecycle as lifecycle

fn on_home_create() -> void
  call ui.show "app.home"
  call lifecycle.ready "app.home"
  text "{title}"
endfn

on app.launch => on_home_create
end
''')
    write(root / "ui/home.eosui", f'''schema: eos-ui-0.1
activity: app.home
window:
  id: app-home
  title: "{title}"
  safe_area: true
  style: app-shell
  children:
    - type: app_bar
      id: home-bar
      title: "{title}"
    - type: text
      id: welcome
      text: "Crea tu primera pantalla EOS"
''')
    write(root / "styles/main.eos.css", '''@activity app.home {
  background: eos.surface;
  color: eos.on-surface;
  safe-area: avoid;
}

#app-home {
  touch-target: comfortable;
  focus-ring: eos.accent;
}
''')
    write(root / "animations/main.eos.yml", '''schema: eos-animation-0.1
animations:
  - id: activity-enter
    target: app-home
    state: enter
    duration_ms: 180
    easing: standard
    property: opacity
    from: 0
    to: 1
''')
    write(root / "policy/permissions.yml", '''schema: eos-permissions-0.1
permissions: []
''')
    write(root / "policy/triggers.yml", '''schema: eos-triggers-0.2
triggers:
  - id: app.launch
    activity: app.home
    handler: on_home_create
    delivery: resumed-only
''')
    write(root / "docs/README.md", f"# {title}\n\nProyecto EOS generado por `eos-sdk`. Edita `ui/`, `styles/`, `animations/`, `policy/` y `src/`.\n")
    write(root / "LICENSE", "EOS development application; replace this license before distribution.\n")
    write(root / "resources/icon.svg", ICON)
    write(root / "resources/splash.svg", SPLASH)
    write(root / "signatures/README.md", "Generated by the official eapp signer; MF files are not source placeholders.\n")


def add_activity(root: Path, activity_id: str, title: str) -> None:
    manifest_path = root / "eapp.json"
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if data.get("format_version") != 3 or not ROUTE.fullmatch(activity_id):
        raise SystemExit("eos-sdk error: v3 project and safe activity id are required")
    definitions = data.setdefault("activities", {}).setdefault("definitions", [])
    if any(item.get("id") == activity_id for item in definitions):
        raise SystemExit(f"eos-sdk error: activity already exists: {activity_id}")
    safe_name = activity_id.replace(".", "_")
    handler = f"on_{safe_name}_create"
    ui_path = f"ui/{safe_name}.eosui"
    definitions.append({"id": activity_id, "title": title, "ui": ui_path, "entry": handler, "exported": False, "orientation": "any", "restore": True})
    write(root / ui_path, f'''schema: eos-ui-0.1
activity: {activity_id}
window:
  id: {safe_name}
  title: "{title}"
  safe_area: true
  children:
    - type: app_bar
      id: {safe_name}-bar
      title: "{title}"
      navigation: back
''')
    triggers = root / "policy/triggers.yml"
    with triggers.open("a", encoding="utf-8") as handle:
        handle.write(f"  # Add app-specific triggers for {activity_id}; handler={handler}\n")
    manifest_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"added activity {activity_id} -> {ui_path}")


def inspect(root: Path) -> None:
    data = json.loads((root / "eapp.json").read_text(encoding="utf-8"))
    activities = data.get("activities", {})
    print(json.dumps({"project": str(root.resolve()), "bundle_id": data.get("identity", {}).get("bundle_id"), "format_version": data.get("format_version"), "main_activity": activities.get("main"), "activity_count": len(activities.get("definitions", [])), "ui": data.get("ui", {}).get("entry"), "source": str(root / "src/main.elang")}, ensure_ascii=False, indent=2))


def main() -> int:
    parser = argparse.ArgumentParser(prog="eos-sdk", description="EOS SDK project generator")
    sub = parser.add_subparsers(dest="command", required=True)
    new = sub.add_parser("new")
    new.add_argument("bundle_id")
    new.add_argument("--output", type=Path, default=None)
    new.add_argument("--author", default="EOS Developer")
    new.add_argument("--title", default=None)
    activity = sub.add_parser("add-activity")
    activity.add_argument("project", type=Path)
    activity.add_argument("activity_id")
    activity.add_argument("--title", required=True)
    check = sub.add_parser("inspect")
    check.add_argument("project", type=Path)
    args = parser.parse_args()
    if args.command == "new":
        if not IDENTIFIER.fullmatch(args.bundle_id):
            raise SystemExit("eos-sdk error: bundle id must look like com.example.app")
        root = (args.output or Path(args.bundle_id.rsplit(".", 1)[-1])).resolve()
        create_project(args.bundle_id, root, args.author, args.title or args.bundle_id.rsplit(".", 1)[-1].title())
        print(f"created EOS Studio project at {root}")
    elif args.command == "add-activity":
        add_activity(args.project.resolve(), args.activity_id, args.title)
    else:
        inspect(args.project.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
